import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import Loading from "@/app/about/loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 元数据 - 页面标题
export const metadata: Metadata = {
  title: "33333",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      {/* Include shared UI here e.g. a header or sidebar */}
      <Suspense fallback={<Loading />}>
        <nav></nav>
        about/layout
        {children}
      </Suspense>
    </section>
  );
}
